### ISSUE TITLE
Can't Run Your Expo Project

### ISSUE THREAD

**Issue by react-native-engineer** [reggie3/payment-example-client#1]
I've tried to run your project after cloning, but it is not running on my mac. it has issues to install packages
Could you help me to run your project?

**Comment by reggie3** [comment]
I don't currently have time to maintain this project, but may come back to it in the future.  I am accepting pull requests though.  Your issues probably arise from the project using an old version of Expo.  An update to the current Expo version could fix the project.

**Comment by react-native-engineer** [comment]
@reggie3, Thanks for your reply.
I am using latest version (32.0). not old version.
I think your library requires old version. 
I am really interested in your library. I don't want to eject my project and want to use paypal and background audio play.
if it is possible, your library will let expo developers to save their time.
I hope to use your library successfully.
Thanks.
